# Generated by Django 2.0.2 on 2021-01-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('Telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('Modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('Color', models.CharField(max_length=50, verbose_name='Color')),
                ('FechaMatri', models.DateField(verbose_name='Fecha de matriculacion')),
                ('Imagen', models.CharField(max_length=50, verbose_name='Imagen')),
                ('Cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cliente')),
            ],
            options={
                'verbose_name': 'Coche',
                'verbose_name_plural': 'Coches',
                'db_table': 'coche',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('Telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Mecanico',
                'verbose_name_plural': 'Mecanicos',
                'db_table': 'mecanico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('Texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('Foto', models.CharField(max_length=50, verbose_name='Foto')),
                ('FechaCreacion', models.DateTimeField(auto_now=True)),
                ('FechaModi', models.DateTimeField(auto_now_add=True)),
                ('Id_Mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Mecanico')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'noticia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaSolicitud', models.DateTimeField(auto_now=True)),
                ('FechaArreglo', models.DateField(verbose_name='Fecha de arreglo')),
                ('Motivo', models.CharField(max_length=500, verbose_name='Motivo')),
                ('Observacion', models.CharField(max_length=500, verbose_name='Observacion')),
                ('Arreglado', models.BooleanField(default=False)),
                ('Id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cliente')),
                ('Id_Coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Coche')),
                ('Id_Mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Mecanico')),
            ],
            options={
                'verbose_name': 'Reparacion',
                'verbose_name_plural': 'Reparaciones',
                'db_table': 'reparacion',
                'ordering': ['id'],
            },
        ),
    ]
