# Generated by Django 2.0.2 on 2021-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='FechaMatri',
            field=models.DateField(null=True, verbose_name='Fecha de matriculacion'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='coche/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='FechaModi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Foto',
            field=models.ImageField(null=True, upload_to='noticia/%Y/%m/%d'),
        ),
    ]
