# Generated by Django 2.0.2 on 2021-02-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20210208_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='FechaMatri',
            field=models.DateField(verbose_name='Fecha de matriculacion'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='coche/%Y/%m/%d'),
        ),
    ]
