# Generated by Django 2.0.2 on 2021-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20210208_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='noticia/%Y/%m/%d'),
        ),
    ]
