# Generated by Django 2.1.5 on 2021-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20210209_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='coche/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='noticia/'),
        ),
    ]
