# Generated by Django 2.1.5 on 2021-02-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auto_20210211_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='Cliente_id',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='Id_Mecanico',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='Id_Cliente',
        ),
    ]
