# Generated by Django 2.1.5 on 2021-02-14 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0008_auto_20210211_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='Id_Mecanico',
            field=models.ManyToManyField(related_name='Mecanicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
