# Generated by Django 3.1.6 on 2021-02-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_reparacion_id_mecanico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coche',
            old_name='Cliente_id',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='Id_Cliente',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='Id_Coche',
            new_name='Coche',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='Id_Mecanico',
            new_name='Mecanico',
        ),
    ]
