# Generated by Django 3.1.6 on 2021-02-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_auto_20210215_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coche',
            old_name='Cliente',
            new_name='Cliente_id',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='Cliente',
            new_name='Id_Cliente',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='Coche',
            new_name='Id_Coche',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='Mecanico',
            new_name='Id_Mecanico',
        ),
    ]
