# Generated by Django 3.1.6 on 2021-02-15 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0012_auto_20210215_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='Id_Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='Id_Mecanico',
            field=models.ManyToManyField(related_name='Mecanicos', to=settings.AUTH_USER_MODEL, verbose_name='Mecanicos'),
        ),
    ]
